### ISSUE TITLE
Instruction for building book is not working

### ISSUE THREAD

**Issue by MartinMSPedersen** [nobozo/progit2-re#1]
**$ bundle install**
Using rake 12.3.2
Using Ascii85 1.0.3
Using public_suffix 3.0.3
Using addressable 2.5.2
Using afm 0.2.2
Using asciidoctor 1.5.6.1
Using mini_portile2 2.1.0
Using nokogiri 1.6.8.1
Using rubyzip 1.2.2
Using gepub 0.6.9.2
Using thread_safe 0.3.6
Using asciidoctor-epub3 1.5.0.alpha.9.dev from https://github.com/asciidoctor/asciidoctor-epub3 (at master@d42f444)
Using pdf-core 0.7.0
Using ttfunk 1.5.1
Using prawn 2.2.2
Using prawn-icon 1.3.0
Using css_parser 1.6.0
Using prawn-svg 0.27.1
Using prawn-table 0.2.2
Using hashery 2.1.2
Using ruby-rc4 0.1.5
Using pdf-reader 2.1.0
Using prawn-templates 0.1.1
Using safe_yaml 1.0.4
Using polyglot 0.3.5
Using treetop 1.5.3
Using asciidoctor-pdf 1.5.0.alpha.16
Using awesome_print 1.8.0
Using bundler 1.16.1
Using coderay 1.1.2
Using epubcheck 3.0.1
Using json 2.1.0
Using kindlegen 3.0.3
Using multi_json 1.13.1
Using pygments.rb 1.2.1
Bundle complete! 11 Gemfile dependencies, 35 gems now installed.
Bundled gems are installed into `./vendor/bundle`

**$ bundle exec rake book:build**
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
progit2-re/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by nobozo** [comment]
Please try now. (During some experimentation on building the book I had added Rakefile to .gitignore so it wasn't committed into the Github repo. I fixed this.)

Thanks for looking at my version of the book.

**Comment by MartinMSPedersen** [comment]
**Thanks.** It works now for me.
